package com.example.javaapidemo.service.impl;

import com.example.javaapidemo.entity.User;
import com.example.javaapidemo.dao.UserRepository;
import com.example.javaapidemo.service.UserService;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

import java.util.Optional;

@Service
public class UserServiceImpl implements UserService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public User addUser(User user){
        return userRepository.save(user);
    }

    public Optional<User> getUserInfo(int id){
        Optional<User> user = userRepository.findById(id);
        System.out.println("user found as follows");
        System.out.println(JSON.toJSON(user));
        return user;
    }

    public Iterable<User> getUserList(){
        Iterable<User> userList = userRepository.findAll();
        return userList;
    }



    public User updateUser(User user){
        return userRepository.save(user); // if not exists then insert new record.
    }

    public String deleteUser(int id){
        userRepository.deleteById(id);
        return "success";
    }
}
